### ISSUE TITLE
Lỗi có thể check-in onchain 2 lần trong cùng một ngày

### ISSUE THREAD

**Issue by haiyenvu23** [Koniverse/Playnation#103]
**Describe the task**
2 giao dịch ở 2 device khác nhau
- Giao dịch-1 là ở máy cty
https://vara.subscan.io/extrinsic/0x9ff8fabb0826daf4a8b24b7dacf78210052637b7ec05601f9fd20292e7a4b93d
- Giao dịch-2 là ở máy nhà
https://vara.subscan.io/extrinsic/0x5027fd7ac71920c360013b65298dd36a10bfeb42488b78289e0c60bbfed84970
=> Đều là check-in onchain và đều thành công

![Image](https://github.com/user-attachments/assets/56e6fe0e-30fc-4f4f-8ba4-0828439ade9a)

Trao đổi ở discord : https://discord.com/channels/1263454418951471174/1268055322317029466

**Comment by anhntk54** [comment]
Hiện issue này a đã đẩy lên dev-03 với cơ chế:
- Nếu nhiệm vụ đã hoàn thành thì khi ấn nhiệm vụ ở thiết bị thứ hai khi sẽ cập nhật view hoàn thành luôn
- Nếu ở thiết bị 1 đang ấn submit, thì ở thiết bị thứ 2 hiện thông báo  nhiệm vụ đang thực hiện
- Nếu ở trường hợp submit thì đang để check trạng thái này trong 30s từ khi user ấn sumitt

**Comment by haiyenvu23** [comment]
- [x] Update cho message thông báo nhiệm vụ đang được thực hiện
  Actual : 


![Image](https://github.com/user-attachments/assets/e6c23cfa-0ef6-4e5c-a5c2-25fa7e4a083a)


  Expect :
- Link notion :  https://www.notion.so/subwallet/Playnation-Chu-n-h-a-message-tr-ng-h-p-check-in-on-chain-tr-n-2-thi-t-b-a7ad82335565480fa77fac345cc81992
- Content : "Mission in progress on another device. Use one device to complete it."

**Comment by haiyenvu23** [comment]
Test on Playnation Dev 03 
Validation passed in case : 
- Nếu nhiệm vụ đã hoàn thành ở thiết bị 1 thì khi ấn nhiệm vụ ở thiết bị thứ hai khi sẽ cập nhật view hoàn thành luôn


![Image](https://github.com/user-attachments/assets/d774a046-133e-422e-b94e-bcb43c2a9b71)

- Nếu ở thiết bị 1 đang ấn submit, thì ở thiết bị thứ 2 hiện thông báo nhiệm vụ đang thực hiện


![Image](https://github.com/user-attachments/assets/e49a2d70-5ab2-4322-a8b2-5c6905e2ae9e)

**Comment by haiyenvu23** [comment]
Re-test on Playnation dev 02 : 
Validation passed in case :

- Nếu nhiệm vụ đã hoàn thành ở thiết bị 1 thì khi ấn nhiệm vụ ở thiết bị thứ hai khi sẽ cập nhật view hoàn thành luôn


![Image](https://github.com/user-attachments/assets/0a347c9f-539e-41d1-a48a-ed11aa1ef353)


- Nếu ở thiết bị 1 đang ấn submit, thì ở thiết bị thứ 2 hiện thông báo nhiệm vụ đang thực hiện


![Image](https://github.com/user-attachments/assets/1772e7a0-b31a-41cc-9073-879593d5028f)
