### ISSUE TITLE
Allows sharing users' scores and ranks on the leaderboard

### ISSUE THREAD

**Issue by hieudd** [Koniverse/Playnation#12]
The feature allows users to share the current score and rank on the campaign leaderboard to Twitter/X.

Share a picture (I don't have a picture yet, I'll temporarily install the Karura camp banner)
Must be able to lead the user back to playnation (If better, get that user's referal link and attach it)

**Content share leaderboard**
Woohoo, I got xxx points and ranked yy on the Karura Token Playdrop leaderboard 🔥

Want some fun and a chance to win Karura airdrop? Join me NOW👇

**Content share airdrop**

A new exciting game is in town, Karura Token Playdrop! Want some fun and a chance to win Karura airdrop? Join me NOW👇

![photo_2024-06-07 17 11 59](https://github.com/Koniverse/Playnation/assets/2582652/3b70fe4a-0a9e-4865-858e-f6f3cc9dd71e)

**Comment by saltict** [comment]
This issue has been resolved
