### ISSUE TITLE
[Report] Invite to play dashboard theo game

### ISSUE THREAD

**Issue by thuytrangpham** [Koniverse/Playnation#128]
- [x]  Invite to play dashboard theo game
- Đối tượng lọc: User invite fren vào một game cụ thể (fren phải chơi game mới được tính là một invite thành công)
- Filter lọc:
    - Thời gian (Ngày, tuần, tháng, total, custom)
    - Game
    - Invite code
- Metric hiển thị trên dashboard: trong ảnh

![Image](https://github.com/user-attachments/assets/c7705b3f-d806-44b0-812b-0f3be67968c2)

**Comment by haiyenvu23** [comment]
Test on https://bi.playnation.app/superset/dashboard/1/?native_filters_key=ea-ch0xGF5TbXUvYrWiAwHCjxVvk1vB98CU2lTvdBJQVSaNeI_cu3IZKkTDnrxU9
- Check với inviteCode : qjDeu7czw
- Data hiển thị đúng khi filter

**Comment by haiyenvu23** [comment]
- [x] Re-check logic công điểm ở cột point
Actual : Thấy không đúng thực tế


![Image](https://github.com/user-attachments/assets/64a4ba25-bb5b-42d5-bcb5-0b5609fd7abb)

**Comment by haiyenvu23** [comment]
Test on : https://bi.playnation.app/superset/dashboard/1/?native_filters_key=DPYx7YhtQe7p6_WQZg3PvKKJnuG3-g1Z4_36-TnfPu7sbqCZQuoa9RkvGaTa7-5_
Validation passed 
NOTE : Thời gian được filter được tính theo thời điểm F1 click vào link invite
