### ISSUE TITLE
Chặn truy cập game trên loại thiết bị cụ thể

### ISSUE THREAD

**Issue by saltict** [Koniverse/Playnation#130]
- [x] Chặn truy cập trên các thiết bị cụ thể theo game:
  - [x] desktop
  - [x] mobile
- [x] Hiển thị thông báo không hỗ trợ hoặc giới hạn thiết bị khi chơi trên thiết bị không thương thích
- [x] Cấu hình CMS
  - [x] Xác định loại thiết bị
  - [x] Cấu hình thông báo lỗi
- [x] View
  - [x] Xử lý thông báo vào UI game (Require thêm content mặc định)

**Comment by Sokol142196** [comment]
Validation passed in cases:
- Chặn webapp
- Chặn mobile
- Chặn desktop app
- Update content
Notes: Không hỗ trợ chặn trên các trình giả lập
