### ISSUE TITLE
Cải tiến leaderboard user mới theo tuần

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/Playnation#131]
**Mô tả**
- Actual: Phần logic sẽ có thể lấy thông tin chính xác của tuần hiện tại nhưng sẽ gặp vấn đề khi mình query theo các tuần cụ thể. Tuần 1, tuần 2, tuần 3... và snapshot để lấy list trả airdrop sau này
- Expect: Update thêm để có thể thể hiện theo từng tuần (Chi tiết trao đổi thêm với anh VA

**Comment by haiyenvu23** [comment]
Test on Playnation Dev 02 : 
Validation passed 
Thông tin trao đổi tại ticket : https://discord.com/channels/1263454418951471174/1270370588510261260
