### ISSUE TITLE
[Mythical Telegram App] UI - Invite friend screen

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/Playnation#148]
![image](https://github.com/user-attachments/assets/55692430-e2f2-4d75-8cbb-17bc14341f53)

- Invite block:
![image](https://github.com/user-attachments/assets/8194e71d-4a5e-4991-8c4b-44bea3792a0f)
- Invite bonus
![image](https://github.com/user-attachments/assets/60d2dfc8-60f2-4db6-93c7-8afe5baacdc2)
- Friend list
![image](https://github.com/user-attachments/assets/7b028267-a15d-42b5-a6f0-7caeb98e8bd6)

**Comment by haiyenvu23** [comment]
- [x] Re-check padding

Actual : 16px

![Image](https://github.com/user-attachments/assets/9187281a-91e9-4457-8ecf-6c34a312194e)

Expect : 19px

**Comment by haiyenvu23** [comment]
Validaton passed 
- Check UI 
- Check responsive
- Update logic => Related to issue https://github.com/Koniverse/Koni-Telegram-Bot/issues/136
