### ISSUE TITLE
[Mythical Telegram App] UI - Login screen

### ISSUE THREAD

**Issue by lw-cdm** [Koniverse/Playnation#153]
![image](https://github.com/user-attachments/assets/8c34d05c-eae5-4328-b281-d40ef0978b24)

- Need to confirm about the design and UX of this screen

**Comment by haiyenvu23** [comment]
- [x] Update according to design 
   Actual : 
   ![Image](https://github.com/user-attachments/assets/d71ef249-97da-47a1-9363-75cb37dc0259)
   Expect : https://www.figma.com/design/ThaXcD1BVdJ8q2y6C3fMZD/SW-Mythical-bot?node-id=1728-31772&t=cytEBoZ56PWbSkev-4

**Comment by haiyenvu23** [comment]
Validation passed 
- Check in mobile, desktop app
![Image](https://github.com/user-attachments/assets/7bc8b695-f9ee-4930-8e8e-7bab2316d56d)
