### ISSUE TITLE
[Story Odyssey] Update default avatar to Story Protocol Masscot and Welcome screen

### ISSUE THREAD

**Issue by saltict** [Koniverse/Playnation#156]
Link design : https://www.figma.com/design/8Fe6aCtYDMqO4BV0s4NHC3/Playnation?node-id=25563-97513&node-type=canvas&t=G8CRuxA1ZmJAWySR-0

- [x] Update default avatar to Story Protocol Mascot
Link design : https://www.figma.com/design/8Fe6aCtYDMqO4BV0s4NHC3/Playnation?node-id=25807-34943&t=G8CRuxA1ZmJAWySR-4
- [x] Update Welcome screen
  - Design: https://www.figma.com/design/8Fe6aCtYDMqO4BV0s4NHC3/Playnation?node-id=25807-34658&t=MliO2piBallGG3z6-4
- [x] Add Mint tab on tabbar
  Actual : 
  ![image](https://github.com/user-attachments/assets/2f9b2895-b889-499a-a37e-1e646385bf8f)

  Expect: Add Mint tab. When click on "Mint" tab then show toast message "Coming soon!"
  ![image](https://github.com/user-attachments/assets/fc732ce4-b057-4928-be48-e52248b12bc8)
- [x] Update Bot name
  - Change to "Koni Story"

**Comment by haiyenvu23** [comment]
Test on @story_protocol_odyssey_dev_bot

- [ ] Update mascot on Checking account screen 
Actual : 
![Image](https://github.com/user-attachments/assets/3c0c9189-4ae9-4191-a26d-9c133c3dd803)

Expect : https://www.figma.com/design/8Fe6aCtYDMqO4BV0s4NHC3/Playnation?node-id=25563-108644&node-type=frame&t=zbMTQAxWnyDMgfji-0

- [ ] Update content for message 
![Image](https://github.com/user-attachments/assets/fc44f28b-d6d1-4e8c-9edb-05df1740f78d)

**Comment by nampc1** [comment]
- [ ] Update showing score criteria
- [ ] Update showing added score screen

**Comment by phamtrang2510** [comment]
Test on @story_protocol_odyssey_dev_bot
Validation passed in case: 

 - Update avata on some screens: 
   - Kickstarting: 
![image](https://github.com/user-attachments/assets/8c7dd13b-d588-475f-adee-18d7ba7f3bb8)
   - Home: 
![image](https://github.com/user-attachments/assets/6927b595-04a3-4f9e-b30e-751067cdbc47)
   - Invite:
![image](https://github.com/user-attachments/assets/65e741e4-a2a3-4bb2-9c38-42f5669f2b00)
   - Leaderboard: 
![image](https://github.com/user-attachments/assets/5867eecb-cc09-40e3-ba46-4f6c80228627)

- Welcome screen:
![image](https://github.com/user-attachments/assets/d070fa75-8f19-4413-826d-272575f47cc2)

- Update content for message: 
![image](https://github.com/user-attachments/assets/e2a3cd3c-2dba-41ba-95ca-84a2e0af0fef)
