### ISSUE TITLE
[Mythical Game] Update mythical linking in Playnation App

### ISSUE THREAD

**Issue by saltict** [Koniverse/Playnation#159]
- Add support mythical login in mythical app

Flow
https://www.figma.com/board/rtxg4Unj0iVV9SEz7mTSys/Mythos-NFL-Rivals-Bot?node-id=0-1&node-type=canvas&t=Kk8NWPSpzJKTAO7e-0

**Comment by nulllpc** [comment]
Done with logic, UI and flow will be completed in this issue https://github.com/Koniverse/Playnation/issues/153
