### ISSUE TITLE
It's difficult to find your position in the Leaderboard and it takes a lot of time

### ISSUE THREAD

**Issue by hieudd** [Koniverse/Playnation#47]
Currently I have to scroll for a long time to find my account
⇒ Suggestion: Stick the user's ranking so that the user can always see and know the ranking position
![Untitled](https://github.com/Koniverse/Playnation/assets/2582652/91979e47-042d-4305-8bbe-d0b877caab58)

**Comment by Sokol142196** [comment]
Currently, this issue is resolved
