### ISSUE TITLE
Add leaderboard in-game

### ISSUE THREAD

**Issue by nulllpc** [Koniverse/Playnation#68]

**Comment by haiyenvu23** [comment]
Test on Booka games

- [x] Check the ranking order again in cases where the scores are equal
Actual : The scores of the two accounts are equal and have the same rank

![Image](https://github.com/user-attachments/assets/ae73fdb7-f788-4824-a4c5-9e69452b2f4a)

- [x] In game, the total score field displays old scores, but on the leaderboard only new scores are counted


![Image](https://github.com/user-attachments/assets/e994a4ce-1dca-405f-af82-bbef30e0c41d)





![Image](https://github.com/user-attachments/assets/cc26cda6-cbcc-4fc7-b990-6fd90f14f104)

**Comment by thuytrangpham** [comment]
- [x] Hiển thị option để user có thể xem xếp hạng theo thời gian ngày/tuần/tháng/Total 
![image](https://github.com/user-attachments/assets/c49da390-2185-434c-ba31-cd729a9fb843)
- [x] Hiển thị Top inviter leaderboard 
- [x] Có thể Tắt/ Bật Leaderboard
Link Notion:
https://www.notion.so/subwallet/Leaderboard-in-game-feature-4451e3ff0e104931b37442fdec3bdbe7

**Comment by Sokol142196** [comment]
@haiyenvu23 các case cơ bản chị thấy ok rồi
Các case nhánh và các điều kiện của các tyoe leaderboard em tiếp tục test giúp c nhé

**Comment by haiyenvu23** [comment]
Test on Playnation Dev 03 :
Validation passed in case :

- Setup trên cms đã áp dụng được trên UI những phần sau :
 - Thêm/Sửa/Xóa leaderboard theo từng bộ lọc :
 - Lọc theo type : game, task, gamePoint, referal, invite to play
 - Lọc theo game : climer, football, ...
 - Lọc theo thời gian : từ ngày -> đến ngày , lọc theo tuần/tháng/năm
 - Thêm trường thông tin để setup button Share hiển thị trên UI
