### ISSUE TITLE
Quy đổi điểm trong game

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/Playnation#73]
**Describe the task**
Quy đổi điểm trong game
Mỗi một game cần một lượt chuyển đổi từ số điểm game sang NPS
- Hiện ở cms cấu hình game bổ sung 1 field để cấu hình tỷ lệ
- Khi người chơi game thì quy đổi số điểm chơi game sang nps theo tý lệ
![image](https://github.com/user-attachments/assets/6578559c-81f4-4aed-9bc8-8723e3738833)

**Comment by Sokol142196** [comment]
- [x] Lỗi quy đổi điểm in game
  - Actual: Tỷ lệ quy đổi đang áp dụng cho cả Total score in game
  - Expect: 
    - Không quy đổi Score in game (tức là user chơi được bao nhiêu điểm trong game thì giữ nguyên
    - Tỷ lệ quy đổi chỉ ảnh hưởng đến việc quy đổi từ Score in game sang NPS

**Comment by haiyenvu23** [comment]
-  Show popup thông báo về thông tin điểm quy đổi
-  Update tỉ lệ quy đổi điểm : chẵn/lẻ -> Disscuss more
=> Related to issue #77

**Comment by haiyenvu23** [comment]
Test on Booka game
Validation passed in case : 
- Target theo mức setup : 
  - Check khi đang ở trong app
  - Check open app
- Quy đổi điểm game sang NPS (Không tác động điểm trong game)
- Chỉ áp dụng thay đổi theo thời điểm hiện tại (không áp dụng cho điểm quá khứ)




![Image](https://github.com/user-attachments/assets/7b54dac2-1fea-429f-9469-8f147f4b5f10)
