### ISSUE TITLE
Tích hợp nhiệm vụ tracking theo game và invite

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/Playnation#74]
**Describe the task**
Tích hợp nhiệm vụ tracking theo game và invite
- Ở cms cấu hình nhiệm vụ để có thể theo dõi 
- Các nhiệm vụ có thể theo dõi được cấu hình theo trường type, còn game sẽ được cấu hình theo game của nhiệm vụ
   - Số người chơi có điểm game ( theo game or tất cả các game)
   - Số người chơi có số lần chơi game ( theo game or tất cả các game)
   - Số lượt người mời chơi f1
![image](https://github.com/user-attachments/assets/74998cc9-4b2f-4ddd-b170-a9acd686aa6d)
- Khi load nhiệm nếu là nhiệm vụ tracking thì hiển thị pont/value ở phầm thực hiện summit nhiệm vụ
![image](https://github.com/user-attachments/assets/2d01efb7-aff2-4498-a3ac-fb341d710747)
Note: Test Action ở UI achivement (Giữa các Missions ở Achievement và các Missions còn lại)

**Comment by Sokol142196** [comment]
- [ ] Tự động hoàn thành nhiệm vụ cho user
  - Actual: User phải bấm Go để hoàn thành nhiệm vụ dù đã track được hoàn thành 2/2
  - Expect: Tự động hoàn thành mission và cộng NPS cho user khi user đã hoàn thành nhiệm vụ

**Comment by Sokol142196** [comment]
> * [ ]  Tự động hoàn thành nhiệm vụ cho user
>   
>   * Actual: User phải bấm Go để hoàn thành nhiệm vụ dù đã track được hoàn thành 2/2
>   * Expect: Tự động hoàn thành mission và cộng NPS cho user khi user đã hoàn thành nhiệm vụ

@anhntk54 please fix this issue

**Comment by anhntk54** [comment]
> > * [ ]   Tự động hoàn thành nhiệm vụ cho user
> >   
> >   * Actual: User phải bấm Go để hoàn thành nhiệm vụ dù đã track được hoàn thành 2/2
> >   * Expect: Tự động hoàn thành mission và cộng NPS cho user khi user đã hoàn thành nhiệm vụ
> 
> @anhntk54 please fix this issue

Cái này a thấy có thể ảnh hưởng đến phần sumbit game đó? nhiều có nhiều nhiệm vụ tracking như thế này?

**Comment by Sokol142196** [comment]
> > > * [ ]    Tự động hoàn thành nhiệm vụ cho user
> > >   
> > >   * Actual: User phải bấm Go để hoàn thành nhiệm vụ dù đã track được hoàn thành 2/2
> > >   * Expect: Tự động hoàn thành mission và cộng NPS cho user khi user đã hoàn thành nhiệm vụ
> > 
> > 
> > [@anhntk54](https://github.com/anhntk54) please fix this issue
> 
> Cái này a thấy có thể ảnh hưởng đến phần sumbit game đó? nhiều có nhiều nhiệm vụ tracking như thế này?

Task này tạm pending nhé ạ, vì nó ko đúng với expect mn đặt ra. Team BA sẽ làm lại doc, mmoo tả rõ ràng hơn rồi mình mới thực hiện tiếp ạ

**Comment by Sokol142196** [comment]
Will resolve in https://github.com/Koniverse/Playnation/issues/117
