### ISSUE TITLE
Support Leaderboard Invite to play

### ISSUE THREAD

**Issue by thuytrangpham** [Koniverse/Playnation#75]
**Description**:

- [x] Đánh giá khả thi: Có khả thi 
- [x] Làm rõ hướng triển khai cho Leaderboard 
       - Prefer: Tách biệt Invite to bot và Invite to play 
       - Cần làm rõ xem khi nào sẽ được cộng NPS: Khi vào bot sẽ tính hay phải chơi game mới tính
- [x] Design: Design tính năng => Dùng Leaderboard cũ

- [x] Triển khai

**Comment by haiyenvu23** [comment]
Test on Megatric
Validation passed in case : 

- Điều kiện cộng điểm invite to bot ( hiển thị account đã click vào link ở màn Manage friend list) : 
   - User click vào link và chưa có tài khoản trên con bot
- Điều kiện hiển thị ở Leaderboard "Invite to play" : 
   - User click vào link và chưa có tài khoản trên con bot
   - User phải chơi game Football
- Cơ chế Ref  : 
    - F0 -> F1 : F0 nhận được số điểm 
    - F1 -> F2 : F1 nhận được số điểm theo từng rank, F0 nhận 5% (sô điểm của F1 nhận được) theo từng rank
- Cơ chế tăng điểm khi acc Ref tăng rank : 
    - F0 -> F1 : F0 nhận được số điểm invite
    - F1 tăng rank : F0 nhận được thêm điểm invite theo từng rank
