### ISSUE TITLE
Disable foodball theme

### ISSUE THREAD

**Issue by saltict** [Koniverse/Playnation#76]
Revert Euro theme, back to normal theme:
https://www.figma.com/design/8Fe6aCtYDMqO4BV0s4NHC3/Playnation?node-id=22298-16108&t=5yAFUtaz8AVUMhtZ-0

**Comment by haiyenvu23** [comment]
Test on Booka enviroment : 
Validation passed 



![Image](https://github.com/user-attachments/assets/06a0b0c3-f766-41c1-a65e-e92c20419edf)


![Image](https://github.com/user-attachments/assets/e7e8f26b-511b-492c-a032-19a4c38313f3)



![Image](https://github.com/user-attachments/assets/12e2afe1-c2c5-456f-a244-b0da60849754)

**Comment by haiyenvu23** [comment]
Test on Booka games : 
Validation passed 


![Image](https://github.com/user-attachments/assets/06a0b0c3-f766-41c1-a65e-e92c20419edf)


![Image](https://github.com/user-attachments/assets/e7e8f26b-511b-492c-a032-19a4c38313f3)



![Image](https://github.com/user-attachments/assets/12e2afe1-c2c5-456f-a244-b0da60849754)


![Image](https://github.com/user-attachments/assets/b88f5f42-44ce-45e7-b2de-3838c3baf914)



![Image](https://github.com/user-attachments/assets/cc57f295-078d-4e45-baa2-d22524d28120)
