### ISSUE TITLE
Hiển thị Tổng NPS của user khi NPS > 100.000

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/Playnation#83]
**Describe the task**
Hiển thị Tổng NPS của user khi NPS > 100.000

**Actual:** Show 100.000+
**Expect:** Show đầy đủ thông tin NPS
- Quy tắc hiển thị khi số lớn: Follow-up và sử dụng lại việc xử lý số của SubWallet

**Comment by lw-cdm** [comment]
Affect areas:

![image](https://github.com/user-attachments/assets/778cd68e-3427-4542-9fe6-20915ff49da8)
---
![image](https://github.com/user-attachments/assets/f6c21394-fd8e-4f82-8b99-b4e059b48082)
---
![image](https://github.com/user-attachments/assets/2465f517-b8ea-4739-b709-041e36338c4a)
---
![image](https://github.com/user-attachments/assets/a6e28667-2828-4ea3-a4a2-9df0dfbf3e19)
---
![image](https://github.com/user-attachments/assets/99237a27-87e9-477a-bbe2-fa06c39ce5df)
---
![image](https://github.com/user-attachments/assets/b72155ed-876a-49d9-9cee-1fe556a52457)

**Comment by haiyenvu23** [comment]
Test on Playnation dev 02
Validation passed in case : 
- Quy tắc hiển thị khi số lớn: Follow-up và sử dụng lại việc xử lý số của SubWallet
- Hiển thị dấu ".", "," theo SubWallet
- Check trên web, mobile ( ios, samsung)
**Note** : Hiện tại chỉ setup trên Strapi đến hàng trăm triệu trở xuống

![Image](https://github.com/user-attachments/assets/a89e8e3a-64d6-40e0-8c0d-b6436de34769)



![Image](https://github.com/user-attachments/assets/4d242470-46e4-4380-9337-9cd33b49ff88)



![Image](https://github.com/user-attachments/assets/4d327b89-a80d-4564-a66b-6332edcf9211)



![Image](https://github.com/user-attachments/assets/e5b92505-6e6d-43a2-a32b-5e24ca35a0e6)
