### ISSUE TITLE
[Report] User level Dashboard

### ISSUE THREAD

**Issue by thuytrangpham** [Koniverse/Playnation#85]
**Describe the task**

- [x]  Dashboard User level data có tất cả thông tin như bảng này và add thêm các metrics: Point balance, Point earn theo game (VD: Kick to drop point, Avail Skyball point,...), accumulated time spent

![Image](https://github.com/user-attachments/assets/8ed25a98-351f-4fa8-b887-2a2bd8dcff5f)

**Comment by anhntk54** [comment]
Anh đã build báo cáo ở tab User 
https://bi.playnation.app/superset/dashboard/1/?native_filters_key=iS10PZDnBiI8gddwfi-4hJz7-NJqYQFW3bxd4j0pd8qMC1oSDH8NnFo9-Uzt_2cW


![Image](https://github.com/user-attachments/assets/2876ee08-cb11-450d-8e91-d2b6ac8800a0)

**Comment by haiyenvu23** [comment]
- [x] Kiểm tra bộ lọc 
Actual : Không search được một số username
Expect : Search được theo username

![Image](https://github.com/user-attachments/assets/ab3e01d4-ae50-4527-9fdd-a6072d31f1e0)
