### ISSUE TITLE
Cải thiện Invite to Play UI

### ISSUE THREAD

**Issue by nulllpc** [Koniverse/Playnation#86]
- [x] Danh sách bạn bè đang bị ngắn do phần thông tin ở phía trên chiếm quá nhiều không gian
- [x] Lúc scroll danh sách bạn bè thì các phần thông tin invite ở trên cần ẩn đi để danh sách bạn bè hiển thị nhiều hơn

**Comment by Sokol142196** [comment]
Bot: @BookaDev02Bot

Validation passed
