### ISSUE TITLE
Thêm cảnh báo khi user thoát app đột ngột

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/Playnation#89]
**Mô tả**
Thêm cảnh báo khi user thoát app đột ngột

**Hướng xử lý**: Sử dụng trực tiếp thông báo thoát app của Telegram

**Comment by Sokol142196** [comment]
Đã triển trên Megatric, @haiyenvu23 test nhanh trên Megatric cho c xem đã hiển thị thông báo chưa nhé

**Comment by haiyenvu23** [comment]
Test on Megatric : 
Validation passed in case : 
- Check on IOS, Android, webapp
- When on logic screen


![Image](https://github.com/user-attachments/assets/b6fb5c71-167b-47a6-9690-90ca1fae9500)

- In game screen


![Image](https://github.com/user-attachments/assets/6765d2e5-d924-45c7-9b1c-93e7c965f816)



![Image](https://github.com/user-attachments/assets/ecd5e901-9f90-4705-aef3-46eeecd5f8c7)
