### ISSUE TITLE
[Report] Add the Invite to Play data field to the Referral Dashboard

### ISSUE THREAD

**Issue by thuytrangpham** [Koniverse/Playnation#92]
**Describe task**

**Hiện tại:** Chưa có trường dữ liệu của Invite to play tại ở Referral Dashboard
**Expect:** Bổ sung trường dữ liệu của Invite to play tại ở Referral Dashboard

![Image](https://github.com/user-attachments/assets/ce2f4c1f-e2f9-4d1c-9040-eb59a73769f9)

**Comment by anhntk54** [comment]
Đã bổ sung 2 trường ở báo cáo  hiện tại:
- Point invite to play
- Number invite to play

**Comment by haiyenvu23** [comment]
Link : https://bi.playnation.app/superset/dashboard/1/?native_filters_key=xfhB_v3f5W8T9Cjvm0zPwTrjmOs4BdNfwS0EQ7DGuoz-bOpVA-s8K9SML7wD4jCK

- [ ] Kiểm tra lại trường hợp Referal point > Accumulate point


![Image](https://github.com/user-attachments/assets/d325d41e-8f8d-4cc7-bbcf-a0f92bbcdd85)

- [ ] Check lại data của cột Indirect referal point/indirect referal number
