### ISSUE TITLE
Check-in onchain task với Creditcoin testnet

### ISSUE THREAD

**Issue by Sokol142196** [Koniverse/Playnation#97]
**Mô tả**
Checkin onchain task với Creditcoin testnet

- [x] Check-on with CTC testnet
- [x] Đánh giá phương án lấy faucet testnet
  - Chốt: Hướng dẫn trên Social, app chỉ hỗ trợ check-in như mission check-in thông thường
  - Doc faucet: https://docs.creditcoin.org/v/cc3/wallets/using-testnet-faucet
- [x] Cần kiểm tra:
  - 1 lần lấy faucet được bao nhiêu => 10 000 CTC
  - Mỗi giao dịch check-in spned tối thiểu bao nhiêu: 0.014 CTC

**Comment by haiyenvu23** [comment]
Test on Playnation Dev 03
Validation passed in case : 
- Test trên web, mobile ( android, ios)
- Thực hiên làm nhiệm vụ với acc có balance 
- Thực hiên làm nhiệm vụ đối với acc không có balance
- Thực hiện mở 1 tài khoản trên 2 thiết bị



https://github.com/user-attachments/assets/6c601799-96c9-4d02-88fd-144a28c61553

**Comment by haiyenvu23** [comment]
Improve UI => Related to issue #102
