### ISSUE TITLE
Thêm thông báo khi thoát game đột ngột (click button X)

### ISSUE THREAD

**Issue by thuytrangpham** [Koniverse/Playnation#98]
**Mô tả**
Khi user click button X khi đang chơi game ⇒ cần thông báo cho user biết để tránh các khiếu nại liên quan về NPS nhận được

**Hướng xử lý:**  Khi user click button X thì hiển thị popup thông báo cho user 
**Header:** Quit game
**Message:**
     Your score and NPS might not be recorded if you quit game now.
     Continue to play?
**CTA:**
    Yes, continue game
    No, quit now

**Comment by Sokol142196** [comment]
Đã chuyển cho anh Quyết để bên Game update
